package com.goodworkalan.addendum;

/**
 * Encapsulates a definition, usually one generated by a definition generator.
 *
 * @author Alan Gutierrez
 */
public interface Definition {
    /**
     * Write a defintion to the given addendum.
     * 
     * @param addendum
     *            The addendum.
     */
    public void define(Addendum addendum);
}
